//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_alm_user")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub alm_user_seq: i32,
  pub alm_user_nm: String,
  pub alm_user_dept: String,
  pub alm_user_mobile: String,
  pub grp_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::tb_alm_sett::Entity")]
  TbAlmSett,
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::GrpId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp,
}

impl Related<super::tb_alm_sett::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbAlmSett.def()
  }
}

impl Related<super::tb_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGrp.def()
  }
}

impl Related<super::tb_water::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_alm_sett::Relation::TbWater.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_alm_sett::Relation::TbAlmUser.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
