//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_alm_water")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub water_seq: i32,
  pub sms_water_stat: Option<String>,
  pub sms_water_stat_dt: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_water::Entity",
    from = "Column::WaterSeq",
    to = "super::tb_water::Column::WaterSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbWater,
}

impl Related<super::tb_water::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbWater.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
