//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_alm_sms_hist")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub alm_sms_hist_seq: i32,
  pub sms_msg: String,
  pub sms_dt: DateTime,
  pub sms_rslt: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
