//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_config")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub grp_id: String,
  #[sea_orm(column_type = "Double")]
  pub def_lat: f64,
  #[sea_orm(column_type = "Double")]
  pub def_lng: f64,
  #[sea_orm(column_type = "Float")]
  pub def_zoom: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::GrpId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp,
}

impl Related<super::tb_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGrp.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
