//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_camera")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub cam_seq: i32,
  pub disp_seq: Option<i32>,
  #[sea_orm(column_type = "Double")]
  pub cam_lat: f64,
  #[sea_orm(column_type = "Double")]
  pub cam_lng: f64,
  pub cam_nm: String,
  pub cam_type: String,
  pub cam_ip: String,
  pub cam_port: i32,
  pub cam_user_id: String,
  pub cam_pass: String,
  pub cam_path_s: String,
  pub cam_path_l: String,
  pub cam_stat: Option<String>,
  pub cam_stat_dt: Option<DateTime>,
  pub grp_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::tb_emcall_grp::Entity")]
  TbEmcallGrp,
  #[sea_orm(has_many = "super::tb_gate::Entity")]
  TbGate,
  #[sea_orm(has_many = "super::tb_gate_camera::Entity")]
  TbGateCamera,
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::GrpId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp,
  #[sea_orm(has_many = "super::tb_water::Entity")]
  TbWater,
}

impl Related<super::tb_emcall_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEmcallGrp.def()
  }
}

impl Related<super::tb_gate_camera::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGateCamera.def()
  }
}

impl Related<super::tb_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGrp.def()
  }
}

impl Related<super::tb_water::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbWater.def()
  }
}

impl Related<super::tb_gate::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_gate_camera::Relation::TbGate.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_gate_camera::Relation::TbCamera.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
