//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_emcall_grp_stat_hist")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub emcall_grp_stat_hist_seq: i32,
  pub emcall_grp_id: String,
  pub emcall_grp_stat_json: Option<String>,
  pub emcall_grp_stat_dt: DateTime,
  pub comm_stat: String,
  pub comm_stat_msg: String,
  pub user_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
