//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_ebrd")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub ebrd_seq: i32,
  pub ebrd_id: String,
  #[sea_orm(column_type = "Double")]
  pub ebrd_lat: f64,
  #[sea_orm(column_type = "Double")]
  pub ebrd_lng: f64,
  pub ebrd_nm: String,
  pub ebrd_ip: String,
  pub ebrd_port: i32,
  pub disp_seq: Option<i32>,
  pub comm_stat: Option<String>,
  pub cmd_rslt: Option<String>,
  pub cmd_rslt_cd: Option<i32>,
  pub ebrd_type: String,
  pub ebrd_emer_msg_pos: Option<i32>,
  pub ebrd_size_w: i32,
  pub ebrd_size_h: i32,
  pub brght_day_lvl: i32,
  pub brght_night_lvl: i32,
  pub ebrd_desc: Option<String>,
  pub day_time_start: String,
  pub day_time_end: String,
  pub on_time_start: String,
  pub on_time_end: String,
  pub send_yn: String,
  pub ebrd_weather_msg: Option<String>,
  pub ebrd_disp_msg: Option<String>,
  pub ebrd_event: Option<String>,
  pub cam_seq: Option<i32>,
  pub grp_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::tb_ebrd_map_msg::Entity")]
  TbEbrdMapMsg,
  #[sea_orm(has_many = "super::tb_gate_ebrd::Entity")]
  TbGateEbrd,
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::GrpId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp,
  #[sea_orm(has_many = "super::tb_ndms_map_ebrd::Entity")]
  TbNdmsMapEbrd,
}

impl Related<super::tb_ebrd_map_msg::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEbrdMapMsg.def()
  }
}

impl Related<super::tb_gate_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGateEbrd.def()
  }
}

impl Related<super::tb_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGrp.def()
  }
}

impl Related<super::tb_ndms_map_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbNdmsMapEbrd.def()
  }
}

impl Related<super::tb_ebrd_msg::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_ebrd_map_msg::Relation::TbEbrdMsg.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_ebrd_map_msg::Relation::TbEbrd.def().rev())
  }
}

impl Related<super::tb_gate::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_gate_ebrd::Relation::TbGate.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_gate_ebrd::Relation::TbEbrd.def().rev())
  }
}

impl Related<super::tcm_flud_board::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_ndms_map_ebrd::Relation::TcmFludBoard.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_ndms_map_ebrd::Relation::TbEbrd.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
