//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_emcall_evt_hist")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub emcall_evt_hist_seq: i32,
  pub emcall_id: String,
  pub comm_stat: String,
  pub emcall_evt_type: String,
  pub emcall_evt_dt: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
