//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_ebrd_map_msg")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub ebrd_seq: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub ebrd_msg_pos: i32,
  pub ebrd_msg_seq: i32,
  pub send_stat: String,
  pub send_rslt: String,
  pub send_dt: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_ebrd::Entity",
    from = "Column::EbrdSeq",
    to = "super::tb_ebrd::Column::EbrdSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbEbrd,
  #[sea_orm(
    belongs_to = "super::tb_ebrd_msg::Entity",
    from = "Column::EbrdMsgSeq",
    to = "super::tb_ebrd_msg::Column::EbrdMsgSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbEbrdMsg,
}

impl Related<super::tb_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEbrd.def()
  }
}

impl Related<super::tb_ebrd_msg::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEbrdMsg.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
