//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_ebrd_msg")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub ebrd_msg_seq: i32,
  pub ebrd_size_w: i32,
  pub ebrd_size_h: i32,
  pub ebrd_msg_text: String,
  pub ebrd_msg_html: String,
  pub ebrd_msg_type: String,
  pub emerg_yn: String,
  pub sound_yn: String,
  pub file_seq: i32,
  pub start_dt: String,
  pub end_dt: String,
  pub start_efct: i32,
  pub end_efct: i32,
  pub start_spd: i32,
  pub end_spd: i32,
  pub start_wait_time: i32,
  pub repeat_cnt: i32,
  pub update_user_id: String,
  pub update_dt: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::tb_ebrd_map_msg::Entity")]
  TbEbrdMapMsg,
  #[sea_orm(
    belongs_to = "super::tb_file::Entity",
    from = "Column::FileSeq",
    to = "super::tb_file::Column::FileSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbFile,
}

impl Related<super::tb_ebrd_map_msg::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEbrdMapMsg.def()
  }
}

impl Related<super::tb_file::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbFile.def()
  }
}

impl Related<super::tb_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_ebrd_map_msg::Relation::TbEbrd.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_ebrd_map_msg::Relation::TbEbrdMsg.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
