//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_emcall")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub emcall_seq: i32,
  #[sea_orm(unique)]
  pub emcall_id: String,
  pub emcall_nm: String,
  #[sea_orm(column_type = "Double")]
  pub emcall_lng: f64,
  #[sea_orm(column_type = "Double")]
  pub emcall_lat: f64,
  pub cam_seq: Option<i32>,
  pub emcall_type: String,
  pub comm_stat: Option<String>,
  pub disp_seq: Option<i32>,
  pub emcall_grp_seq: i32,
  pub grp_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_emcall_grp::Entity",
    from = "Column::EmcallGrpSeq",
    to = "super::tb_emcall_grp::Column::EmcallGrpSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbEmcallGrp,
  #[sea_orm(has_many = "super::tb_gate_emcall::Entity")]
  TbGateEmcall,
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::GrpId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp,
}

impl Related<super::tb_emcall_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEmcallGrp.def()
  }
}

impl Related<super::tb_gate_emcall::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGateEmcall.def()
  }
}

impl Related<super::tb_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGrp.def()
  }
}

impl Related<super::tb_gate::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_gate_emcall::Relation::TbGate.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_gate_emcall::Relation::TbEmcall.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
