//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_ebrd_hist")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub ebrd_hist_seq: i32,
  pub ebrd_seq: i32,
  pub ebrd_id: String,
  pub comm_stat: String,
  pub update_dt: DateTime,
  #[sea_orm(column_type = "Text")]
  pub json: String,
  pub cmd_rslt: Option<String>,
  pub cmd_rslt_cd: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
