//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_emcall_grp")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub emcall_grp_seq: i32,
  #[sea_orm(unique)]
  pub emcall_grp_id: String,
  pub emcall_grp_nm: String,
  pub emcall_grp_ip: String,
  pub emcall_grp_port: i32,
  #[sea_orm(column_type = "Double", nullable)]
  pub emcall_grp_lng: Option<f64>,
  #[sea_orm(column_type = "Double", nullable)]
  pub emcall_grp_lat: Option<f64>,
  pub emcall_type: String,
  pub comm_stat: Option<String>,
  pub cam_seq: Option<i32>,
  pub emcall_tts_msg: Option<String>,
  pub grp_id: String,
  pub emcall_grp_stat_json: Option<String>,
  pub disp_seq: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_camera::Entity",
    from = "Column::CamSeq",
    to = "super::tb_camera::Column::CamSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbCamera,
  #[sea_orm(has_many = "super::tb_emcall::Entity")]
  TbEmcall,
  #[sea_orm(has_many = "super::tb_gate_emcall_grp::Entity")]
  TbGateEmcallGrp,
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::GrpId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp,
}

impl Related<super::tb_camera::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbCamera.def()
  }
}

impl Related<super::tb_emcall::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEmcall.def()
  }
}

impl Related<super::tb_gate_emcall_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGateEmcallGrp.def()
  }
}

impl Related<super::tb_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGrp.def()
  }
}

impl Related<super::tb_gate::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_gate_emcall_grp::Relation::TbGate.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_gate_emcall_grp::Relation::TbEmcallGrp.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
