//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_file")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub file_seq: i32,
  pub file_nm: String,
  pub file_size: i32,
  #[sea_orm(column_type = "Binary(255)")]
  pub file_data: Vec<u8>,
  pub file_ref_cnt: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::tb_board::Entity")]
  TbBoard,
  #[sea_orm(has_many = "super::tb_ebrd_msg::Entity")]
  TbEbrdMsg,
  #[sea_orm(has_one = "super::tb_file_tmp::Entity")]
  TbFileTmp,
}

impl Related<super::tb_board::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbBoard.def()
  }
}

impl Related<super::tb_ebrd_msg::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEbrdMsg.def()
  }
}

impl Related<super::tb_file_tmp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbFileTmp.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
