//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_file_tmp")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub file_seq: i32,
  pub update_dt: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_file::Entity",
    from = "Column::FileSeq",
    to = "super::tb_file::Column::FileSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbFile,
}

impl Related<super::tb_file::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbFile.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
