//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_grp_tree")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub parent_id: String,
  #[sea_orm(primary_key, auto_increment = false)]
  pub child_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::ParentId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp2,
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::ChildId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp1,
}

impl ActiveModelBehavior for ActiveModel {}
