//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_gate_hist")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub gate_hist_seq: i32,
  pub gate_seq: i32,
  pub gate_stat: String,
  pub cmd_req: String,
  pub cmd_rslt: String,
  pub cmd_rslt_msg: Option<String>,
  pub update_dt: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
