//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_grp")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub grp_id: String,
  pub grp_nm: String,
  pub grp_desc: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::tb_alm_user::Entity")]
  TbAlmUser,
  #[sea_orm(has_many = "super::tb_book_mark::Entity")]
  TbBookMark,
  #[sea_orm(has_many = "super::tb_camera::Entity")]
  TbCamera,
  #[sea_orm(has_one = "super::tb_config::Entity")]
  TbConfig,
  #[sea_orm(has_many = "super::tb_ebrd::Entity")]
  TbEbrd,
  #[sea_orm(has_many = "super::tb_emcall::Entity")]
  TbEmcall,
  #[sea_orm(has_many = "super::tb_emcall_grp::Entity")]
  TbEmcallGrp,
  #[sea_orm(has_many = "super::tb_gate::Entity")]
  TbGate,
  #[sea_orm(has_many = "super::tb_group::Entity")]
  TbGroup,
  #[sea_orm(has_many = "super::tb_login::Entity")]
  TbLogin,
  #[sea_orm(has_many = "super::tb_region::Entity")]
  TbRegion,
  #[sea_orm(has_many = "super::tb_water::Entity")]
  TbWater,
}

impl Related<super::tb_alm_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbAlmUser.def()
  }
}

impl Related<super::tb_book_mark::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbBookMark.def()
  }
}

impl Related<super::tb_camera::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbCamera.def()
  }
}

impl Related<super::tb_config::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbConfig.def()
  }
}

impl Related<super::tb_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEbrd.def()
  }
}

impl Related<super::tb_emcall::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEmcall.def()
  }
}

impl Related<super::tb_emcall_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEmcallGrp.def()
  }
}

impl Related<super::tb_gate::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGate.def()
  }
}

impl Related<super::tb_group::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGroup.def()
  }
}

impl Related<super::tb_login::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbLogin.def()
  }
}

impl Related<super::tb_region::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbRegion.def()
  }
}

impl Related<super::tb_water::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbWater.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
