//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_gate")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub gate_seq: i32,
  pub disp_seq: Option<i32>,
  #[sea_orm(column_type = "Double")]
  pub gate_lat: f64,
  #[sea_orm(column_type = "Double")]
  pub gate_lng: f64,
  pub gate_nm: String,
  pub gate_ip: String,
  pub gate_port: i32,
  pub gate_type: String,
  pub down_type: String,
  pub auto_down_cond: Option<String>,
  pub gate_no: Option<i32>,
  pub cam_seq: Option<i32>,
  pub gate_stat: Option<String>,
  pub cmd_rslt: Option<String>,
  pub ebrd_oper_mode: Option<String>,
  pub emcall_oper_mode: Option<String>,
  pub grp_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_camera::Entity",
    from = "Column::CamSeq",
    to = "super::tb_camera::Column::CamSeq",
    on_update = "SetNull",
    on_delete = "SetNull"
  )]
  TbCamera,
  #[sea_orm(has_many = "super::tb_gate_camera::Entity")]
  TbGateCamera,
  #[sea_orm(has_many = "super::tb_gate_ebrd::Entity")]
  TbGateEbrd,
  #[sea_orm(has_many = "super::tb_gate_emcall::Entity")]
  TbGateEmcall,
  #[sea_orm(has_many = "super::tb_gate_emcall_grp::Entity")]
  TbGateEmcallGrp,
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::GrpId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp,
  #[sea_orm(has_many = "super::tb_ndms_map_gate::Entity")]
  TbNdmsMapGate,
  #[sea_orm(has_many = "super::tb_water_gate::Entity")]
  TbWaterGate,
}

impl Related<super::tb_gate_camera::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGateCamera.def()
  }
}

impl Related<super::tb_gate_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGateEbrd.def()
  }
}

impl Related<super::tb_gate_emcall::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGateEmcall.def()
  }
}

impl Related<super::tb_gate_emcall_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGateEmcallGrp.def()
  }
}

impl Related<super::tb_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGrp.def()
  }
}

impl Related<super::tb_ndms_map_gate::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbNdmsMapGate.def()
  }
}

impl Related<super::tb_water_gate::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbWaterGate.def()
  }
}

impl Related<super::tb_camera::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_gate_camera::Relation::TbCamera.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_gate_camera::Relation::TbGate.def().rev())
  }
}

impl Related<super::tb_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_gate_ebrd::Relation::TbEbrd.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_gate_ebrd::Relation::TbGate.def().rev())
  }
}

impl Related<super::tb_emcall::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_gate_emcall::Relation::TbEmcall.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_gate_emcall::Relation::TbGate.def().rev())
  }
}

impl Related<super::tb_emcall_grp::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_gate_emcall_grp::Relation::TbEmcallGrp.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_gate_emcall_grp::Relation::TbGate.def().rev())
  }
}

impl Related<super::tb_water::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_water_gate::Relation::TbWater.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_water_gate::Relation::TbGate.def().rev())
  }
}

impl Related<super::tcm_flud_car_intrcp::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_ndms_map_gate::Relation::TcmFludCarIntrcp.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_ndms_map_gate::Relation::TbGate.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
