//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_gate_emcall_grp")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub gate_seq: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub emcall_grp_seq: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_emcall_grp::Entity",
    from = "Column::EmcallGrpSeq",
    to = "super::tb_emcall_grp::Column::EmcallGrpSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbEmcallGrp,
  #[sea_orm(
    belongs_to = "super::tb_gate::Entity",
    from = "Column::GateSeq",
    to = "super::tb_gate::Column::GateSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGate,
}

impl Related<super::tb_emcall_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEmcallGrp.def()
  }
}

impl Related<super::tb_gate::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGate.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
