//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_group")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub grp_seq: i32,
  pub grp_type: String,
  pub grp_nm: String,
  pub grp_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::tb_group_el::Entity")]
  TbGroupEl,
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::GrpId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp,
}

impl Related<super::tb_group_el::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGroupEl.def()
  }
}

impl Related<super::tb_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGrp.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
