//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_group_el")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub grp_seq: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub grp_el_seq: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_group::Entity",
    from = "Column::GrpSeq",
    to = "super::tb_group::Column::GrpSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGroup,
}

impl Related<super::tb_group::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGroup.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
