//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_log")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub log_seq: i32,
  pub user_id: String,
  pub log_level: String,
  pub log_msg: String,
  pub log_data_json: String,
  pub log_dt: DateTime,
  pub log_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
