//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_ndms_map_water")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub flcode: String,
  #[sea_orm(primary_key, auto_increment = false)]
  pub cd_dist_wal: i32,
  pub water_seq: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_water::Entity",
    from = "Column::WaterSeq",
    to = "super::tb_water::Column::WaterSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbWater,
  #[sea_orm(
    belongs_to = "super::tcm_flud_wal::Entity",
    from = "(Column::Flcode, Column::CdDistWal)",
    to = "(super::tcm_flud_wal::Column::Flcode, super::tcm_flud_wal::Column::CdDistWal)",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TcmFludWal,
}

impl Related<super::tb_water::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbWater.def()
  }
}

impl Related<super::tcm_flud_wal::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TcmFludWal.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
