//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_ndms_map_ebrd")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub flcode: String,
  #[sea_orm(primary_key, auto_increment = false)]
  pub cd_dist_board: i32,
  pub ebrd_seq: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_ebrd::Entity",
    from = "Column::EbrdSeq",
    to = "super::tb_ebrd::Column::EbrdSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbEbrd,
  #[sea_orm(
    belongs_to = "super::tcm_flud_board::Entity",
    from = "(Column::Flcode, Column::CdDistBoard)",
    to = "(super::tcm_flud_board::Column::Flcode, super::tcm_flud_board::Column::CdDistBoard)",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TcmFludBoard,
}

impl Related<super::tb_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbEbrd.def()
  }
}

impl Related<super::tcm_flud_board::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TcmFludBoard.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
