//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_ncd")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub ncd_grp: String,
  #[sea_orm(primary_key, auto_increment = false)]
  pub ncd_id: i32,
  pub ncd_nm: String,
  pub ncd_seq: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
