//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_ndms_map_gate")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub flcode: String,
  #[sea_orm(primary_key, auto_increment = false)]
  pub cd_dist_intrcp: i32,
  pub gate_seq: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_gate::Entity",
    from = "Column::GateSeq",
    to = "super::tb_gate::Column::GateSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGate,
  #[sea_orm(
    belongs_to = "super::tcm_flud_car_intrcp::Entity",
    from = "(Column::Flcode, Column::CdDistIntrcp)",
    to = "(super::tcm_flud_car_intrcp::Column::Flcode, super::tcm_flud_car_intrcp::Column::CdDistIntrcp)",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TcmFludCarIntrcp,
}

impl Related<super::tb_gate::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGate.def()
  }
}

impl Related<super::tcm_flud_car_intrcp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TcmFludCarIntrcp.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
