//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_sys_conf")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub sys_conf_id: String,
  pub login_logo_file_seq: Option<i32>,
  pub logo_file_seq: Option<i32>,
  pub api_key_weather: Option<String>,
  pub api_key_map: Option<String>,
  pub url_offline_map: Option<String>,
  pub use_offline_map_yn: Option<String>,
  pub use_water_yn: Option<String>,
  pub use_ebrd_yn: Option<String>,
  pub use_emcall_yn: Option<String>,
  pub use_emcall_grp_yn: Option<String>,
  pub use_gate_yn: Option<String>,
  pub use_camera_yn: Option<String>,
  pub use_weather_yn: Option<String>,
  pub use_ndms_yn: Option<String>,
  pub use_sms_yn: Option<String>,
  pub use_rtsp_svr_yn: Option<String>,
  pub rtsp_svr_ip_port: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
