//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_water_grp")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub water_seq: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub lnk_water_seq: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_water::Entity",
    from = "Column::LnkWaterSeq",
    to = "super::tb_water::Column::WaterSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbWater2,
  #[sea_orm(
    belongs_to = "super::tb_water::Entity",
    from = "Column::LnkWaterSeq",
    to = "super::tb_water::Column::WaterSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbWater1,
}

impl ActiveModelBehavior for ActiveModel {}
