//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_water_gate")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub water_seq: i32,
  #[sea_orm(primary_key, auto_increment = false)]
  pub gate_seq: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::tb_gate::Entity",
    from = "Column::GateSeq",
    to = "super::tb_gate::Column::GateSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGate,
  #[sea_orm(
    belongs_to = "super::tb_water::Entity",
    from = "Column::WaterSeq",
    to = "super::tb_water::Column::WaterSeq",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbWater,
}

impl Related<super::tb_gate::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGate.def()
  }
}

impl Related<super::tb_water::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbWater.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
