//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_water_hist")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub water_hist_seq: i32,
  pub water_dev_id: String,
  pub water_dt: DateTime,
  #[sea_orm(column_type = "Double")]
  pub water_level: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
