//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_water")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub water_seq: i32,
  pub disp_seq: Option<i32>,
  #[sea_orm(unique)]
  pub water_dev_id: String,
  pub water_gate_seq: Option<i32>,
  pub water_nm: String,
  #[sea_orm(column_type = "Double")]
  pub water_lat: f64,
  #[sea_orm(column_type = "Double")]
  pub water_lng: f64,
  pub water_mod: String,
  pub cam_seq: Option<i32>,
  #[sea_orm(column_type = "Double")]
  pub limit_attn: f64,
  #[sea_orm(column_type = "Double")]
  pub limit_warn: f64,
  #[sea_orm(column_type = "Double")]
  pub limit_alert: f64,
  #[sea_orm(column_type = "Double")]
  pub limit_crit: f64,
  pub water_type: String,
  pub water_dt: Option<DateTime>,
  #[sea_orm(column_type = "Double", nullable)]
  pub water_level: Option<f64>,
  pub water_stat: Option<String>,
  pub comm_stat: Option<String>,
  pub grp_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::tb_alm_sett::Entity")]
  TbAlmSett,
  #[sea_orm(has_one = "super::tb_alm_water::Entity")]
  TbAlmWater,
  #[sea_orm(
    belongs_to = "super::tb_camera::Entity",
    from = "Column::CamSeq",
    to = "super::tb_camera::Column::CamSeq",
    on_update = "SetNull",
    on_delete = "SetNull"
  )]
  TbCamera,
  #[sea_orm(
    belongs_to = "super::tb_grp::Entity",
    from = "Column::GrpId",
    to = "super::tb_grp::Column::GrpId",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  TbGrp,
  #[sea_orm(has_many = "super::tb_ndms_map_water::Entity")]
  TbNdmsMapWater,
  #[sea_orm(has_many = "super::tb_water_gate::Entity")]
  TbWaterGate,
}

impl Related<super::tb_alm_sett::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbAlmSett.def()
  }
}

impl Related<super::tb_alm_water::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbAlmWater.def()
  }
}

impl Related<super::tb_camera::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbCamera.def()
  }
}

impl Related<super::tb_grp::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbGrp.def()
  }
}

impl Related<super::tb_ndms_map_water::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbNdmsMapWater.def()
  }
}

impl Related<super::tb_water_gate::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbWaterGate.def()
  }
}

impl Related<super::tb_alm_user::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_alm_sett::Relation::TbAlmUser.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_alm_sett::Relation::TbWater.def().rev())
  }
}

impl Related<super::tb_gate::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_water_gate::Relation::TbGate.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_water_gate::Relation::TbWater.def().rev())
  }
}

impl Related<super::tcm_flud_wal::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_ndms_map_water::Relation::TcmFludWal.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_ndms_map_water::Relation::TbWater.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
