//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tb_weather")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub wt_seq: i32,
  pub wt_rgn_nm: String,
  #[sea_orm(column_type = "Double")]
  pub wt_lat: f64,
  #[sea_orm(column_type = "Double")]
  pub wt_lng: f64,
  pub disp_seq: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
