//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tcm_flud_board")]
pub struct Model {
  #[sea_orm(column_name = "FLCODE", primary_key, auto_increment = false)]
  pub flcode: String,
  #[sea_orm(column_name = "CD_DIST_BOARD", primary_key, auto_increment = false)]
  pub cd_dist_board: i32,
  #[sea_orm(column_name = "NM_DIST_BOARD")]
  pub nm_dist_board: String,
  #[sea_orm(column_name = "COMM_STTUS")]
  pub comm_sttus: Option<String>,
  #[sea_orm(column_name = "MSG_BOARD")]
  pub msg_board: Option<String>,
  #[sea_orm(column_name = "LAT", column_type = "Double", nullable)]
  pub lat: Option<f64>,
  #[sea_orm(column_name = "LON", column_type = "Double", nullable)]
  pub lon: Option<f64>,
  #[sea_orm(column_name = "RM")]
  pub rm: Option<String>,
  #[sea_orm(column_name = "USE_YN")]
  pub use_yn: String,
  #[sea_orm(column_name = "RGSDE")]
  pub rgsde: DateTime,
  #[sea_orm(column_name = "UPDDE")]
  pub updde: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_one = "super::tb_ndms_map_ebrd::Entity")]
  TbNdmsMapEbrd,
}

impl Related<super::tb_ndms_map_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbNdmsMapEbrd.def()
  }
}

impl Related<super::tb_ebrd::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_ndms_map_ebrd::Relation::TbEbrd.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_ndms_map_ebrd::Relation::TcmFludBoard.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
