//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tcm_cou_dngr_almord")]
pub struct Model {
  #[sea_orm(column_name = "DSCODE", primary_key, auto_increment = false)]
  pub dscode: String,
  #[sea_orm(column_name = "CD_DIST_OBSV", primary_key, auto_increment = false)]
  pub cd_dist_obsv: i32,
  #[sea_orm(column_name = "ALMCODE", primary_key, auto_increment = false)]
  pub almcode: String,
  #[sea_orm(column_name = "ALMDE", primary_key, auto_increment = false)]
  pub almde: String,
  #[sea_orm(column_name = "ALMGB", primary_key, auto_increment = false)]
  pub almgb: String,
  #[sea_orm(column_name = "ALMNOTE")]
  pub almnote: Option<String>,
  #[sea_orm(column_name = "ADMCODE")]
  pub admcode: String,
  #[sea_orm(column_name = "RGSDE")]
  pub rgsde: DateTime,
  #[sea_orm(column_name = "UPDDE")]
  pub updde: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
