//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tcm_cou_dngr_adm")]
pub struct Model {
  #[sea_orm(column_name = "ADMCODE", primary_key, auto_increment = false)]
  pub admcode: String,
  #[sea_orm(column_name = "CHPSNNM")]
  pub chpsnnm: String,
  #[sea_orm(column_name = "CHARGE_DEPT")]
  pub charge_dept: String,
  #[sea_orm(column_name = "CTTPC")]
  pub cttpc: String,
  #[sea_orm(column_name = "RM")]
  pub rm: Option<String>,
  #[sea_orm(column_name = "USE_YN")]
  pub use_yn: String,
  #[sea_orm(column_name = "RGSDE")]
  pub rgsde: DateTime,
  #[sea_orm(column_name = "UPDDE")]
  pub updde: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
