//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tcm_flud_almord")]
pub struct Model {
  #[sea_orm(column_name = "FLCODE", primary_key, auto_increment = false)]
  pub flcode: String,
  #[sea_orm(column_name = "CD_DIST_INTRCP", primary_key, auto_increment = false)]
  pub cd_dist_intrcp: i32,
  #[sea_orm(column_name = "STTUSDE", primary_key, auto_increment = false)]
  pub sttusde: String,
  #[sea_orm(column_name = "INTRCP_STTUS", primary_key, auto_increment = false)]
  pub intrcp_sttus: String,
  #[sea_orm(column_name = "RM")]
  pub rm: Option<String>,
  #[sea_orm(column_name = "ADMCODE")]
  pub admcode: String,
  #[sea_orm(column_name = "RGSDE")]
  pub rgsde: DateTime,
  #[sea_orm(column_name = "UPDDE")]
  pub updde: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
