//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tcm_flud_spot")]
pub struct Model {
  #[sea_orm(column_name = "FLCODE", primary_key, auto_increment = false)]
  pub flcode: String,
  #[sea_orm(column_name = "FLNAME")]
  pub flname: String,
  #[sea_orm(column_name = "FLADDR")]
  pub fladdr: String,
  #[sea_orm(column_name = "BDONG_CD")]
  pub bdong_cd: String,
  #[sea_orm(column_name = "LAT", column_type = "Double", nullable)]
  pub lat: Option<f64>,
  #[sea_orm(column_name = "LON", column_type = "Double", nullable)]
  pub lon: Option<f64>,
  #[sea_orm(column_name = "ADVSRY_WAL", column_type = "Double", nullable)]
  pub advsry_wal: Option<f64>,
  #[sea_orm(column_name = "ALARM_WAL", column_type = "Double", nullable)]
  pub alarm_wal: Option<f64>,
  #[sea_orm(column_name = "FLUD_WAL", column_type = "Double", nullable)]
  pub flud_wal: Option<f64>,
  #[sea_orm(column_name = "RM")]
  pub rm: Option<String>,
  #[sea_orm(column_name = "ADMCODE")]
  pub admcode: String,
  #[sea_orm(column_name = "USE_YN")]
  pub use_yn: String,
  #[sea_orm(column_name = "RGSDE")]
  pub rgsde: DateTime,
  #[sea_orm(column_name = "UPDDE")]
  pub updde: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
