//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tcm_flud_wal")]
pub struct Model {
  #[sea_orm(column_name = "FLCODE", primary_key, auto_increment = false)]
  pub flcode: String,
  #[sea_orm(column_name = "CD_DIST_WAL", primary_key, auto_increment = false)]
  pub cd_dist_wal: i32,
  #[sea_orm(column_name = "NM_DIST_WAL")]
  pub nm_dist_wal: String,
  #[sea_orm(column_name = "GB_WAL")]
  pub gb_wal: Option<String>,
  #[sea_orm(column_name = "LAST_COLCT_DE")]
  pub last_colct_de: Option<String>,
  #[sea_orm(column_name = "LAST_COLCT_WAL", column_type = "Double", nullable)]
  pub last_colct_wal: Option<f64>,
  #[sea_orm(column_name = "LAT", column_type = "Double", nullable)]
  pub lat: Option<f64>,
  #[sea_orm(column_name = "LON", column_type = "Double", nullable)]
  pub lon: Option<f64>,
  #[sea_orm(column_name = "RM")]
  pub rm: Option<String>,
  #[sea_orm(column_name = "USE_YN")]
  pub use_yn: String,
  #[sea_orm(column_name = "RGSDE")]
  pub rgsde: DateTime,
  #[sea_orm(column_name = "UPDDE")]
  pub updde: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_one = "super::tb_ndms_map_water::Entity")]
  TbNdmsMapWater,
}

impl Related<super::tb_ndms_map_water::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TbNdmsMapWater.def()
  }
}

impl Related<super::tb_water::Entity> for Entity {
  fn to() -> RelationDef {
    super::tb_ndms_map_water::Relation::TbWater.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::tb_ndms_map_water::Relation::TcmFludWal.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
